In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("sales_data_sample.csv", encoding="latin1")


In [5]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small


In [7]:
arr = df.to_numpy()



In [8]:
arr 

array([[10107, 30, 95.7, ..., 'Yu', 'Kwai', 'Small'],
       [10121, 34, 81.35, ..., 'Henriot', 'Paul', 'Small'],
       [10134, 41, 94.74, ..., 'Da Cunha', 'Daniel', 'Medium'],
       ...,
       [10386, 43, 100.0, ..., 'Freyre', 'Diego', 'Medium'],
       [10397, 34, 62.24, ..., 'Roulet', 'Annette', 'Small'],
       [10414, 47, 65.52, ..., 'Yoshido', 'Juri', 'Medium']],
      shape=(2823, 25), dtype=object)

In [6]:
print(arr.shape)

(2823, 25)


In [10]:
print(arr[0])
print(arr[-1])

print(arr[:,4])
print(arr[2,:])

[10107 30 95.7 2 2871.0 '2/24/2003 0:00' 'Shipped' 1 2 2003 'Motorcycles'
 95 'S10_1678' 'Land of Toys Inc.' '2125557818' '897 Long Airport Avenue'
 nan 'NYC' 'NY' '10022' 'USA' nan 'Yu' 'Kwai' 'Small']
[10414 47 65.52 9 3079.44 '5/6/2005 0:00' 'On Hold' 2 5 2005 'Ships' 54
 'S72_3212' 'Gifts4AllAges.com' '6175559555' '8616 Spinnaker Dr.' nan
 'Boston' 'MA' '51003' 'USA' nan 'Yoshido' 'Juri' 'Medium']
[2871.0 2765.9 3884.34 ... 5417.57 2116.16 3079.44]
[10134 41 94.74 2 3884.34 '7/1/2003 0:00' 'Shipped' 3 7 2003 'Motorcycles'
 95 'S10_1678' 'Lyon Souveniers' '+33 1 46 62 7555'
 '27 rue du Colonel Pierre Avia' nan 'Paris' nan '75508' 'France' 'EMEA'
 'Da Cunha' 'Daniel' 'Medium']


In [12]:
print(arr[:,2])
print(arr[2,2])

[95.7 81.35 94.74 ... 100.0 62.24 65.52]
94.74


In [14]:
priceeach = arr[:,2]
print(priceeach + 5)
print(priceeach - 5)
print(priceeach * 5)
print(priceeach / 5)

[100.7 86.35 99.74 ... 105.0 67.24000000000001 70.52]
[90.7 76.35 89.74 ... 95.0 57.24 60.519999999999996]
[478.5 406.75 473.7 ... 500.0 311.2 327.59999999999997]
[19.14 16.27 18.948 ... 20.0 12.448 13.104]


In [15]:
sales = arr[:,4]
print(sales > 3000)
print(sales < 3000)
print(sales == 3000)

[False False  True ...  True False  True]
[ True  True False ... False  True False]
[False False False ... False False False]


In [17]:
print(sales[sales > 3000])
print(sales[sales < 3000])

[3884.34 3746.7 5205.27 ... 3978.51 5417.57 3079.44]
[2871.0 2765.9 2497.77 ... 2227.6 2244.4 2116.16]


In [19]:
print(np.sum(arr[:, 2]))
print(np.sum(arr[:, 1]))
print(np.sum(arr[:, 3]))
print(np.sum(arr[:, 4]))

236168.07000000044
99067
18254
10032628.85000001


In [21]:
print(np.mean(arr[:, 2]))
print(np.mean(arr[:, 4]))
print(np.mean(arr[2, 2]))

83.65854410201929
3553.88907190932
94.74


In [22]:
print(np.median(arr[:, 2]))
print(np.median(arr[:, 3]))
print(np.median(arr[:, 4]))

95.7
6.0
3184.8


In [23]:
print(np.min(arr[:, 3]))
print(np.max(arr[:, 3]))

print(np.min(arr[:, 4]))
print(np.max(arr[:, 4]))

1
18
482.13
14082.8


In [24]:
print(np.std(arr[:, 2]))
print(np.std(arr[:, 3]))


20.170703013238615
4.225092432054711


In [25]:
print(np.var(arr[:, 2]))
print(np.var(arr[:, 3]))


406.8572600482733
17.851406059405992


In [37]:
sales = arr[1:5,1:4]
print(sales)
print(np.mean(sales, axis=0))
print(np.median(sales, axis=1))
print(np.mean(sales, axis=1))


[[34 81.35 5]
 [41 94.74 2]
 [45 83.26 6]
 [49 100.0 14]]
[42.25 89.83749999999999 6.75]
[34.0 41.0 45.0 49.0]
[40.11666666666667 45.913333333333334 44.75333333333333 54.333333333333336]


In [44]:
average = np.mean(arr[:, 2:5], axis=1)
index = np.argmax(average)
index1 = np.argmin(average)
print(index)
print(index1)


598
2249


In [46]:
print(np.sort(arr[:,2]))
print(np.sort(arr[:,3]))

[26.88 27.22 28.29 ... 100.0 100.0 100.0]
[1 1 1 ... 18 18 18]


In [48]:
print(np.unique(arr[:,2]))
print(np.unique(arr[:,3]))

[26.88 27.22 28.29 ... 99.82 99.91 100.0]
[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18]


In [49]:
ORDERLINENUMBER	 = arr[:,3]

result = np.where(ORDERLINENUMBER<7,ORDERLINENUMBER + 10,ORDERLINENUMBER)

print(result)

[12 15 12 ... 14 11 9]


In [52]:
index = np.argmax(arr[:, 2])
index1 = np.argmin(arr[:, 2])

print(index)
print(index1)

4
1563


In [59]:
arr = np.arange(1,13)
print(arr)
print(arr.shape)
print(arr.reshape(4,3))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [62]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.flatten())
print(arr1.transpose())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [63]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print(np.concatenate((arr1,arr2)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [65]:
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [69]:
print(np.zeros(5))
print(np.ones(5))

print(np.zeros((4,3)))
print(np.ones((5,2)))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [70]:
print(np.linspace(0, 100, 11))

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [76]:
random_marks = np.random.randint(1,100,size=10)
print(random_marks)
print(np.random.randint(5))
print(np.random.rand(3,3))

[98 24  5 16 98 81 51 91 13 15]
0
[[0.17681019 0.53974876 0.53516425]
 [0.40004918 0.66385574 0.47910387]
 [0.7569757  0.62623763 0.75918337]]


In [82]:
marks = np.array([80, 90, np.nan, 70, 85])
print(marks)
mean_value = np.nanmean(marks)
print(mean_value)
print(np.isnan(marks))
print(np.sum(np.isnan(marks)))

marks[np.isnan(marks)]= mean_value
print(marks)

[80. 90. nan 70. 85.]
81.25
[False False  True False False]
1
[80.   90.   81.25 70.   85.  ]
